### ISSUE TITLE
XSLT Processing Error upon installation

### ISSUE THREAD

**Issue by diomed** [bernardodiasc/remember-x#4]
hi. I installed this in localhost and it displays this error on my front page, instead web page:

`XSLTProcessor::importStylesheet():
    compilation error: file file:///D:/xampp/htdocs/remember/ line 3 element import
    xsl:import : invalid URI reference D:\xampp\htdocs\remember/workspace/pages/index.xsl
XSLTProcessor::transformToXml():
    No stylesheet associated to this object`

**Comment by bernardodiasc** [comment]
hey @diomed, on this project I'm using Symphony from integration branch, since this is not a production project. This approach helps to locate and fix bugs for next releases.

I've updated the latest from integration, can you check is this bug is fixed.

Please let me know if you continue seeing this bug.

**Comment by diomed** [comment]
It's all good now in that area. 
There are some other issues:

#1.Dropping images to upload doesn't work
#2. All of those things that are in demo in admin area displayed in sidebar, fall down, below text area.
#3. Tweets don't display in oembed [maybe they need special css? i'm not sure. however, they don't.

**Comment by bernardodiasc** [comment]
Awesome! So this issue is working now? Lets close so to avoid confusion.

Can you please open separated issues for each case?

in advance, the item 1 and 2 are probably bugs related to the extensions, not exactly fault of this ensemble. Also, if you check on XSL, this project is still very crude, some fields will not display in the frontend, __yet!__

The item 2 I dont get exactly, please open an new issue for it, if possible with more information and screenshots :)

**Comment by diomed** [comment]
I've also realised that Epic Editor extension caused problem no 2.
You don't have it installed in demo, but in github version it exists.
Unnecessary, IMO. After removing it, layout came back to normal. :ok_hand:

**Comment by bernardodiasc** [comment]
Ah, yeah, thanks for remember me about this. There is some extensions that I let disabled in my setup, but when install via ensemble all extensions are installed. I'll fix this now!

**Comment by bernardodiasc** [comment]
Done, removed the following extensions:

- dashboard
- epiceditor
- markdown_editor
- markdown_guide
- markdown_typography
- sirtrevor_formatter
- templatedtextformatters

Thanks @diomed, really appreciate your feedback!
